# Generated by Django 3.2.8 on 2021-10-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=264, unique=True)),
                ('description', models.TextField(blank=True, max_length=1200)),
                ('category_image', models.ImageField(blank=True, upload_to='images/category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'caregories',
            },
        ),
    ]
