# Generated by Django 3.2.8 on 2021-11-25 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_line_1',
            field=models.CharField(default=datetime.datetime(2021, 11, 25, 15, 38, 1, 415970, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=datetime.datetime(2021, 11, 25, 15, 38, 36, 42799, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default=datetime.datetime(2021, 11, 25, 15, 38, 46, 950264, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2021, 11, 25, 15, 38, 55, 96965, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2021, 11, 25, 15, 39, 4, 466884, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_note',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=datetime.datetime(2021, 11, 25, 15, 39, 14, 148735, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default=datetime.datetime(2021, 11, 25, 15, 39, 27, 15123, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
