# Generated by Django 3.2.8 on 2021-11-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20211126_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grant_total',
            field=models.FloatField(default=1.0),
        ),
    ]
